### ISSUE TITLE
Zeus abilities damage returning None

### ISSUE THREAD

**Issue by IagoBeuller** [mdiller/dotabase#5]
At least for Zeus, his abilities's damage return None, only the ability of index 1 return the damage. May have other heroes with the same issue.

**Comment by mdiller** [comment]
Hey thanks for making an issue! So this is a bit of a tricky thing. The purpose of dotabase is to get the data from the dota 2 source files and present it in a more refined and usable/reliable format. Because I'm just building this ontop of the data I'm given, I try to not change it too much so im not too reliant on the way they store the data.

At the end of the day, what this means for this "Damage" field for spells is that I'm just grabbing this from the "AbilityDamage" field of the spell data. If you look at the json_data field of the spells you'll see why theres a difference, because the damage on arc lightning is in a completely different place. The way I decided to present this data into a usable format is to parse all of that "AbilitySpecial" data into its own special thing, and attach any headers i can find for them from the localization files.Thats why you can find the "DAMAGE:" header in the ability_special of arc lightning.

You could say "well we should detect that and put it in the 'Damage' field". For arc lightning that kindof makes sense, but theres tons of spells out there that have multiple damage number sources for a single spell. For example for qop's Shadow Strike, it has the initial damage and also the damage over time. There isn't really a clear choice as to which one to show. For these reasons I think its best that I just pass on the data as its presented from the dota files, and in cases like that just leave it blank.

Short answer here is that if the "Damage" field is none, then take a look at the ability_special and see what you can do with that data. Mangobyte (a discord bot I made that uses dotabase) uses both of these to create the spell descriptions which look like this:
![image](https://user-images.githubusercontent.com/3231343/163920056-eb14bc55-630e-4a3c-bb12-d592d64a88e0.png)
![image](https://user-images.githubusercontent.com/3231343/163920077-e46593a5-bc0f-4456-a29f-0e7d0a7508bc.png)
